### ISSUE TITLE
Fetching Supplemental Table members

### ISSUE THREAD

**Issue by andrei-shabanski** [spothero/py-responsys#12]
I found that the client doesn't have a method to fetch members of a Supplemental Table http://docs.oracle.com/cloud/latest/marketingcs_gs/OMCED/op-rest-api-v1.3-folders-%7BfolderName%7D-suppData-%7BtableName%7D-members-get.html

Could you please implement this method? It would be very useful for me

**Comment by andrei-shabanski** [comment]
I've added PR https://github.com/spothero/py-responsys/pull/14

**Comment by nbkincaid** [comment]
@andrei-shabanski Thank you for adding this, I've merged your pr.
